name: Preview & Sync gh-pages
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build
        run: |
          cd ${{secrets.CLIENT}}
          npm install
          VUE_APP_BASE_URL=${{secrets.BASE_URL}} VUE_APP_IMG_URL=${{secrets.IMG_URL}} npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ${{secrets.CLIENT}}/dist

  sync:
    needs: [preview]
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Sync Gitee
        uses: shanghaobo/github-branch-gitee@master
        with:
          github_repo: savoygu/message-timeline
          github_branch: gh-pages
          gitee_repo: gusaifei/message-timeline-gh-pages
          gitee_branch: master
          username: ${{secrets.GITEE_USERNAME}}
          password: ${{secrets.GITEE_PASSWORD}}
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{secrets.GITEE_USERNAME}}
          gitee-password: ${{secrets.GITEE_PASSWORD}}
          gitee-repo: gusaifei/message-timeline-gh-pages
          branch: master
